version: '3.5'

services:
  nodejs:
    build: .
    container_name: webpack-base
    hostname: webpack-base
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./src:/home/node/app/src
      - ./dist:/home/node/app/dist
      - ./webpack.config.js:/home/node/app/webpack.config.js
      - ./postcss.config.js:/home/node/app/postcss.config.js
    tty: true
    ports:
      - 8979:8979
